### ISSUE TITLE
Add viewer capability

### ISSUE THREAD

**Issue by koernigo** [jankapunkt/meteor-autoform-bpmn#8] opened 2018-08-07 15:05 UTC
Feature Request

Short description of the feature:

Provide an easy way to simply view the BPMN flow vs. editing it, i.e. looking at the flow w/o the sidebars etc. Ideally it wouldn’t be an image, but something you can interact with (e…g. hover over and see description or being able to navigate to sub-proc…

Use-case (why would anyone besides you need this feature, too):

Once a flow has been created it will likely more used to view, monitor and execute vs. continued editing.  Having a viewer would help in many cases.

Possible next steps:

Leverage bpmn.io viewer and integrate as an additional AutoForm

**Comment by jankapunkt** [comment] 2018-08-09 20:38
Fixed in new version 0.1.5

When a form is in mode `"disabled"` the `NavigatedViewer` is used instead of `Modeler`.

Please note

- there is currently still no support to reactively switch between view and edit mode but I will add it asap, please see #9
- currently this feature is fixed, there is currently no option to suppress the view mode by the schema (if there is a use case that makes sense, where you need finer control of it, please create a new issue with detailed description)
- tests are added but coverage is still by ~70% which is not sufficient enough to me

**Closed by jankapunkt** 2018-08-09 20:38 UTC

**Comment by koernigo** [comment] 2018-08-09 22:16
Hi, I just tried this out and it doesn't seem to work for me (using the example app) When I click on the view button it brings up the same view. or is this the issue you were referring to?

**Comment by jankapunkt** [comment] 2018-08-10 09:40
It seems that the example app did not pull the latest 0.1.5 version but remained at 0.1.4. I just hard coded the version in the meteor packages. Please pull the example app and try again.

**Comment by koernigo** [comment] 2018-08-13 08:52
Just installed the new version. I get the following errors in Google Chrome
![image](https://user-images.githubusercontent.com/31516395/44022059-8e80596e-9eb4-11e8-9d98-bfd1e26e237e.png)

**Comment by jankapunkt** [comment] 2018-08-13 10:39
Did you use the example project? Since I don't have this error I would need something to reproduce it.

**Comment by koernigo** [comment] 2018-08-13 11:06
Hi, some more detail. I deleted the project directory and started with a clean install.

Here is my console window. Maybe it's an issue with the Meteor version?

[root@localhost okoernig]# git clone thttps://github.com/jankapunkt/meteor-autoform-bpmn-example.git
Cloning into 'meteor-autoform-bpmn-example'...
fatal: Unable to find remote helper for 'thttps'
[root@localhost okoernig]# git clone https://github.com/jankapunkt/meteor-autoform-bpmn-example.git
Cloning into 'meteor-autoform-bpmn-example'...
remote: Counting objects: 126, done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 126 (delta 18), reused 35 (delta 15), pack-reused 83
Receiving objects: 100% (126/126), 117.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (46/46), done.
[root@localhost okoernig]# cd met*
[root@localhost meteor-autoform-bpmn-example]# ls
client  imports  LICENSE  package.json  package-lock.json  README.md  run.sh  screenshot.png  server
[root@localhost meteor-autoform-bpmn-example]# meteor npm install
added 338 packages in 12.423s
[root@localhost meteor-autoform-bpmn-example]# ./run.sh
up to date in 6.801s

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your permissions,
run the following command from the root of your project:

  sudo chown -Rh <username> .meteor/local

                                              
Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app directory will be incorrect if you ever attempt to perform any Meteor tasks as a normal user. If you need to fix your permissions,
run the following command from the root of your project:

  sudo chown -Rh <username> .meteor/local

[[[[[ /home/okoernig/meteor-autoform-bpmn-example ]]]]]

=> Started proxy.                             
=> A patch (Meteor 1.6.1.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
I20180813-07:03:02.092(-4)? ** You've set up some data subscriptions with Meteor.publish(), but
I20180813-07:03:02.190(-4)? ** you still have autopublish turned on. Because autopublish is still
I20180813-07:03:02.191(-4)? ** on, your Meteor.publish() calls won't have much effect. All data
I20180813-07:03:02.191(-4)? ** will still be sent to all clients.
I20180813-07:03:02.191(-4)? **
I20180813-07:03:02.191(-4)? ** Turn off autopublish by removing the autopublish package:
I20180813-07:03:02.192(-4)? **
I20180813-07:03:02.192(-4)? **   $ meteor remove autopublish
I20180813-07:03:02.192(-4)? **
I20180813-07:03:02.192(-4)? ** .. and make sure you have Meteor.publish() and Meteor.subscribe() calls
I20180813-07:03:02.192(-4)? ** for each collection that you want clients to see.
I20180813-07:03:02.192(-4)? 
=> Started your app.

=> App running at: http://localhost:9999

**Comment by jankapunkt** [comment] 2018-08-13 13:35
Can confirm this. Again a big struggle with babel runtime, similar to #10 

I will check on that.

**Comment by jankapunkt** [comment] 2018-08-13 14:00
Seems to be fixed when patching the meteor version and updating the packages. When the ci finally runs through I will merge it into the master. The latest state is now on the branch "fixci" where you can already pull the latest. Would be nice to hear if it works. I will check tonight again on it.
